GET  http://127.0.0.1:8000/train
Content-Type: application/json
################################
POST  http://127.0.0.1:8000/
Content-Type: application/json

{
    "question": "xinchao"
}
#######################
GET https://chatbot-capstone1.herokuapp.com/train
Content-Type: application/json